apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol01
spec:
  capacity:
    storage: 300Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/export/vol01
    server: services.lab.example.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol02
spec:
  capacity:
    storage: 300Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/export/vol02
    server: services.lab.example.com
