apiVersion: v1
kind: Template
metadata:
  name: nexus
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    generation: 1
    name: ${NEXUS_SERVICE_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: registry.lab.example.com:5000/do288/nexus3:latest
      generation: 1
      importPolicy:
        insecure: true
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    generation: 1
    labels:
      app: ${NEXUS_SERVICE_NAME}
    name: ${NEXUS_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      app: ${NEXUS_SERVICE_NAME}
      deploymentconfig: ${NEXUS_SERVICE_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
        labels:
          app: ${NEXUS_SERVICE_NAME}
          deploymentconfig: ${NEXUS_SERVICE_NAME}
      spec:
        containers:
        - imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/liveness.sh
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          name: ${NEXUS_SERVICE_NAME}
          ports:
          - containerPort: 8081
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /usr/local/bin/readiness.sh
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /nexus-data
            name: nexus-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data-pvc
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NEXUS_SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: nexus3:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: ${NEXUS_SERVICE_NAME}
    name: ${NEXUS_SERVICE_NAME}
  spec:
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: ${NEXUS_SERVICE_NAME}
      deploymentconfig: ${NEXUS_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${NEXUS_SERVICE_NAME}
    name: ${NEXUS_SERVICE_NAME}
  spec:
    host: ${HOSTNAME}
    port:
      targetPort: 8081-tcp
    to:
      kind: Service
      name: ${NEXUS_SERVICE_NAME}
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2017-11-29T16:57:34Z
        status: "True"
        type: Admitted
      host: ${HOSTNAME}
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
    name: nexus-data-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 300Mi
  status: {}
parameters:
- name: HOSTNAME
  displayName: Aplication Hostname
  description: FQDN of the route to access the application
  required: true

- name: NEXUS_SERVICE_NAME
  displayName: Nexus Service Name
  description: The name of the OpenShift Service exposed for the nexus server.
  required: true
  value: nexus3
